<?php

/**
 * Implements hook_permission().
 */
function maritpal_pricing_permission() {
  return array(
    'create pricing rules' => array(
      'title' => t('Create pricing rules'),
      'description' => t('Allows to create pricing rules.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function maritpal_pricing_menu() {
  $items = array();

  $items['admin/add/pricing-rule'] = array(
    'title' => 'Add pricing rule',
    'description' => 'Pricing rule form.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('maritpal_pricing_form'),
    'access callback' => TRUE
  );

  // $items['add/pricing-rule'] = array(
  //   'title' => 'Rule added',
  //   'page callback' => '_rules_admin_install_example_rules',
  //   'access callback' => TRUE
  // );

  return $items;
}

/**
 * Implements hook_form().
 */
function maritpal_pricing_form($form, &$form_state) {

	$matches = array();
	$or = db_or()
		-> condition('vid', '14', '=')
		-> condition('vid', '13', '=');

  $result = db_select('taxonomy_term_data', 't')
    -> fields('t', array('tid', 'name', 'vid'))
    -> condition($or)
    -> execute();

  foreach ($result as $term) {
  	if ( $term -> vid == '14' ) {
    	$matches['location'][$term -> tid] = check_plain($term -> name);
  	} elseif ( $term -> vid == '13' ) {
    	$matches['category'][$term -> tid] = check_plain($term -> name);
  	}
  }

	// $form['#action'] = url('add/pricing-rule');

	$form['rule_title'] = array(
    '#type' => 'textfield',
    '#title' => 'Title',
    '#size' => 255,
    '#maxlength' => 255,
    '#description' => t('Unique title of pricing rule.'),
    '#required' => TRUE,
  );

  $form['service_location'] = array(
		'#type' => 'select',
		'#title' => t('Location'),
		'#options' => $matches['location'],
		'#default_value' => $category['selected'],
		'#description' => t('Service location Country or City.'),
	);

	$form['service_category'] = array(
		'#type' => 'select',
		'#title' => t('Service category'),
		'#options' => $matches['category'],
		'#default_value' => $category['selected'],
		'#description' => t('Service categury.'),
	);

	$form['service_price_per_hour'] = array(
    '#type' => 'textfield',
    '#title' => 'Price per hour',
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Price for an 1 hour.'),
    '#required' => TRUE,
  );

	$form['service_rate'] = array(
    '#type' => 'textfield',
    '#title' => 'Service rate',
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Integer or decimal rate.'),
    '#required' => TRUE,
  );
  
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Add rule'),
  );
  
  return $form;
}

/**
 * Implements hook_form_validate().
 */
function maritpal_pricing_form_validate($form, &$form_state) {

	if (!($form_state['values']['price_per_hour'] > 0)){
    form_set_error('price_per_hour', t('Price must be a positive number.'));
  }

}

function maritpal_pricing_form_submit($form, &$form_state) {
}

// function maritpal_pricing_default_rules_configuration() {
// }

